import { Location } from '../types/location';

export const locations: Location[] = [
  // Alabama
  {
    id: "pinterest-marketing-agency-alabama",
    name: "Alabama",
    state: "AL",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "2100 3rd Avenue North, Suite 400, Birmingham, AL 35203",
    marketSize: "850K users",
    avgGrowth: "38%",
    clientCount: 28,
  },
  // Alaska
  {
    id: "pinterest-marketing-agency-alaska",
    name: "Alaska",
    state: "AK",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "500 W 2nd Avenue, Suite 200, Anchorage, AK 99501",
    marketSize: "180K users",
    avgGrowth: "35%",
    clientCount: 12,
  },
  // Arizona
  {
    id: "pinterest-marketing-agency-arizona",
    name: "Arizona",
    state: "AZ",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "2 N Central Avenue, Suite 1800, Phoenix, AZ 85004",
    marketSize: "3.2M users",
    avgGrowth: "56%",
    clientCount: 78,
  },
  // Arkansas
  {
    id: "pinterest-marketing-agency-arkansas",
    name: "Arkansas",
    state: "AR",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "400 W Capitol Avenue, Suite 2600, Little Rock, AR 72201",
    marketSize: "520K users",
    avgGrowth: "42%",
    clientCount: 21,
  },
  // California - Los Angeles
  {
    id: "pinterest-marketing-agency-california",
    name: "California",
    state: "CA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "456 Sunset Blvd, Suite 789, Los Angeles, CA 90028",
    marketSize: "4.2M users",
    avgGrowth: "52%",
    clientCount: 89,
  },
  // California - San Francisco
  {
    id: "pinterest-marketing-agency-california-sf",
    name: "California",
    state: "CA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "123 Market Street, Suite 456, San Francisco, CA 94102",
    marketSize: "2.3M users",
    avgGrowth: "55%",
    clientCount: 67,
  },
  // California - San Diego
  {
    id: "pinterest-marketing-agency-california-sd",
    name: "California",
    state: "CA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "600 B Street, Suite 300, San Diego, CA 92101",
    marketSize: "1.8M users",
    avgGrowth: "49%",
    clientCount: 54,
  },
  // Colorado
  {
    id: "pinterest-marketing-agency-colorado",
    name: "Colorado",
    state: "CO",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1515 Wynkoop Street, Suite 300, Denver, CO 80202",
    marketSize: "1.6M users",
    avgGrowth: "61%",
    clientCount: 47,
  },
  // Connecticut
  {
    id: "pinterest-marketing-agency-connecticut",
    name: "Connecticut",
    state: "CT",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "280 Trumbull Street, Suite 2500, Hartford, CT 06103",
    marketSize: "920K users",
    avgGrowth: "44%",
    clientCount: 31,
  },
  // Delaware
  {
    id: "pinterest-marketing-agency-delaware",
    name: "Delaware",
    state: "DE",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "919 Market Street, Suite 1700, Wilmington, DE 19801",
    marketSize: "280K users",
    avgGrowth: "39%",
    clientCount: 16,
  },
  // Florida - Miami
  {
    id: "pinterest-marketing-agency-florida",
    name: "Florida",
    state: "FL",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "321 Ocean Drive, Suite 654, Miami, FL 33139",
    marketSize: "2.1M users",
    avgGrowth: "58%",
    clientCount: 45,
  },
  // Florida - Orlando
  {
    id: "pinterest-marketing-agency-florida-orlando",
    name: "Florida",
    state: "FL",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "201 S Orange Avenue, Suite 725, Orlando, FL 32801",
    marketSize: "1.4M users",
    avgGrowth: "54%",
    clientCount: 38,
  },
  // Florida - Tampa
  {
    id: "pinterest-marketing-agency-florida-tampa",
    name: "Florida",
    state: "FL",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "100 N Tampa Street, Suite 4000, Tampa, FL 33602",
    marketSize: "1.2M users",
    avgGrowth: "51%",
    clientCount: 35,
  },
  // Georgia
  {
    id: "pinterest-marketing-agency-georgia",
    name: "Georgia",
    state: "GA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "233 Peachtree Street NE, Suite 2000, Atlanta, GA 30303",
    marketSize: "2.8M users",
    avgGrowth: "53%",
    clientCount: 72,
  },
  // Hawaii
  {
    id: "pinterest-marketing-agency-hawaii",
    name: "Hawaii",
    state: "HI",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1001 Bishop Street, Suite 1800, Honolulu, HI 96813",
    marketSize: "380K users",
    avgGrowth: "46%",
    clientCount: 19,
  },
  // Idaho
  {
    id: "pinterest-marketing-agency-idaho",
    name: "Idaho",
    state: "ID",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "802 W Bannock Street, Suite 900, Boise, ID 83702",
    marketSize: "420K users",
    avgGrowth: "48%",
    clientCount: 22,
  },
  // Illinois
  {
    id: "pinterest-marketing-agency-illinois",
    name: "Illinois",
    state: "IL",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "789 Michigan Ave, Suite 321, Chicago, IL 60611",
    marketSize: "2.8M users",
    avgGrowth: "41%",
    clientCount: 73,
  },
  // Indiana
  {
    id: "pinterest-marketing-agency-indiana",
    name: "Indiana",
    state: "IN",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "One Monument Circle, Suite 2700, Indianapolis, IN 46204",
    marketSize: "1.1M users",
    avgGrowth: "43%",
    clientCount: 33,
  },
  // Iowa
  {
    id: "pinterest-marketing-agency-iowa",
    name: "Iowa",
    state: "IA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "666 Grand Avenue, Suite 2500, Des Moines, IA 50309",
    marketSize: "480K users",
    avgGrowth: "40%",
    clientCount: 24,
  },
  // Kansas
  {
    id: "pinterest-marketing-agency-kansas",
    name: "Kansas",
    state: "KS",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "200 W Douglas Avenue, Suite 920, Wichita, KS 67202",
    marketSize: "550K users",
    avgGrowth: "41%",
    clientCount: 26,
  },
  // Kentucky
  {
    id: "pinterest-marketing-agency-kentucky",
    name: "Kentucky",
    state: "KY",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "400 W Market Street, Suite 2000, Louisville, KY 40202",
    marketSize: "720K users",
    avgGrowth: "39%",
    clientCount: 29,
  },
  // Louisiana
  {
    id: "pinterest-marketing-agency-louisiana",
    name: "Louisiana",
    state: "LA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "650 Poydras Street, Suite 1800, New Orleans, LA 70130",
    marketSize: "780K users",
    avgGrowth: "45%",
    clientCount: 32,
  },
  // Maine
  {
    id: "pinterest-marketing-agency-maine",
    name: "Maine",
    state: "ME",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "511 Congress Street, Suite 200, Portland, ME 04101",
    marketSize: "320K users",
    avgGrowth: "37%",
    clientCount: 18,
  },
  // Maryland
  {
    id: "pinterest-marketing-agency-maryland",
    name: "Maryland",
    state: "MD",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "100 Light Street, Suite 1200, Baltimore, MD 21202",
    marketSize: "1.3M users",
    avgGrowth: "46%",
    clientCount: 41,
  },
  // Massachusetts
  {
    id: "pinterest-marketing-agency-massachusetts",
    name: "Massachusetts",
    state: "MA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1 Boston Place, Suite 2600, Boston, MA 02108",
    marketSize: "2.1M users",
    avgGrowth: "48%",
    clientCount: 58,
  },
  // Michigan
  {
    id: "pinterest-marketing-agency-michigan",
    name: "Michigan",
    state: "MI",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "500 Griswold Street, Suite 2700, Detroit, MI 48226",
    marketSize: "1.8M users",
    avgGrowth: "44%",
    clientCount: 52,
  },
  // Minnesota
  {
    id: "pinterest-marketing-agency-minnesota",
    name: "Minnesota",
    state: "MN",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "800 Nicollet Mall, Suite 2500, Minneapolis, MN 55402",
    marketSize: "1.4M users",
    avgGrowth: "47%",
    clientCount: 42,
  },
  // Mississippi
  {
    id: "pinterest-marketing-agency-mississippi",
    name: "Mississippi",
    state: "MS",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "188 E Capitol Street, Suite 1000, Jackson, MS 39201",
    marketSize: "410K users",
    avgGrowth: "36%",
    clientCount: 20,
  },
  // Missouri - Kansas City
  {
    id: "pinterest-marketing-agency-missouri",
    name: "Missouri",
    state: "MO",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1100 Main Street, Suite 2600, Kansas City, MO 64105",
    marketSize: "1.2M users",
    avgGrowth: "45%",
    clientCount: 37,
  },
  // Missouri - St. Louis
  {
    id: "pinterest-marketing-agency-missouri-stl",
    name: "Missouri",
    state: "MO",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "100 N Broadway, Suite 1000, St. Louis, MO 63102",
    marketSize: "980K users",
    avgGrowth: "42%",
    clientCount: 34,
  },
  // Montana
  {
    id: "pinterest-marketing-agency-montana",
    name: "Montana",
    state: "MT",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "2800 3rd Avenue North, Suite 400, Billings, MT 59101",
    marketSize: "240K users",
    avgGrowth: "44%",
    clientCount: 15,
  },
  // Nebraska
  {
    id: "pinterest-marketing-agency-nebraska",
    name: "Nebraska",
    state: "NE",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1623 Farnam Street, Suite 600, Omaha, NE 68102",
    marketSize: "620K users",
    avgGrowth: "43%",
    clientCount: 27,
  },
  // Nevada
  {
    id: "pinterest-marketing-agency-nevada",
    name: "Nevada",
    state: "NV",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "300 S 4th Street, Suite 1400, Las Vegas, NV 89101",
    marketSize: "1.5M users",
    avgGrowth: "59%",
    clientCount: 46,
  },
  // New Hampshire
  {
    id: "pinterest-marketing-agency-new-hampshire",
    name: "New Hampshire",
    state: "NH",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "900 Elm Street, Suite 400, Manchester, NH 03101",
    marketSize: "360K users",
    avgGrowth: "41%",
    clientCount: 19,
  },
  // New Jersey
  {
    id: "pinterest-marketing-agency-new-jersey",
    name: "New Jersey",
    state: "NJ",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1 Newark Center, Suite 1800, Newark, NJ 07102",
    marketSize: "2.4M users",
    avgGrowth: "45%",
    clientCount: 61,
  },
  // New Mexico
  {
    id: "pinterest-marketing-agency-new-mexico",
    name: "New Mexico",
    state: "NM",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "625 Silver Avenue SW, Suite 320, Albuquerque, NM 87102",
    marketSize: "580K users",
    avgGrowth: "50%",
    clientCount: 25,
  },
  // New York - NYC
  {
    id: "pinterest-marketing-agency-new-york",
    name: "New York",
    state: "NY",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "123 Broadway, Suite 456, New York, NY 10001",
    marketSize: "8.4M users",
    avgGrowth: "47%",
    clientCount: 127,
  },
  // New York - Buffalo
  {
    id: "pinterest-marketing-agency-new-york-buffalo",
    name: "New York",
    state: "NY",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "200 Delaware Avenue, Suite 1200, Buffalo, NY 14202",
    marketSize: "680K users",
    avgGrowth: "38%",
    clientCount: 28,
  },
  // North Carolina - Charlotte
  {
    id: "pinterest-marketing-agency-north-carolina",
    name: "North Carolina",
    state: "NC",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "100 N Tryon Street, Suite 5000, Charlotte, NC 28202",
    marketSize: "1.6M users",
    avgGrowth: "52%",
    clientCount: 48,
  },
  // North Carolina - Raleigh
  {
    id: "pinterest-marketing-agency-north-carolina-raleigh",
    name: "North Carolina",
    state: "NC",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "421 Fayetteville Street, Suite 1100, Raleigh, NC 27601",
    marketSize: "980K users",
    avgGrowth: "49%",
    clientCount: 36,
  },
  // North Dakota
  {
    id: "pinterest-marketing-agency-north-dakota",
    name: "North Dakota",
    state: "ND",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "400 Roberts Street, Suite 200, Fargo, ND 58102",
    marketSize: "180K users",
    avgGrowth: "40%",
    clientCount: 13,
  },
  // Ohio - Columbus
  {
    id: "pinterest-marketing-agency-ohio",
    name: "Ohio",
    state: "OH",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "41 S High Street, Suite 2500, Columbus, OH 43215",
    marketSize: "1.4M users",
    avgGrowth: "44%",
    clientCount: 43,
  },
  // Ohio - Cleveland
  {
    id: "pinterest-marketing-agency-ohio-cleveland",
    name: "Ohio",
    state: "OH",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "127 Public Square, Suite 4900, Cleveland, OH 44114",
    marketSize: "1.1M users",
    avgGrowth: "41%",
    clientCount: 39,
  },
  // Oklahoma
  {
    id: "pinterest-marketing-agency-oklahoma",
    name: "Oklahoma",
    state: "OK",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "210 Park Avenue, Suite 2550, Oklahoma City, OK 73102",
    marketSize: "780K users",
    avgGrowth: "46%",
    clientCount: 30,
  },
  // Oregon
  {
    id: "pinterest-marketing-agency-oregon",
    name: "Oregon",
    state: "OR",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "121 SW Morrison Street, Suite 1100, Portland, OR 97204",
    marketSize: "1.3M users",
    avgGrowth: "53%",
    clientCount: 44,
  },
  // Pennsylvania - Philadelphia
  {
    id: "pinterest-marketing-agency-pennsylvania",
    name: "Pennsylvania",
    state: "PA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1650 Market Street, Suite 3600, Philadelphia, PA 19103",
    marketSize: "2.2M users",
    avgGrowth: "43%",
    clientCount: 59,
  },
  // Pennsylvania - Pittsburgh
  {
    id: "pinterest-marketing-agency-pennsylvania-pittsburgh",
    name: "Pennsylvania",
    state: "PA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "600 Grant Street, Suite 4400, Pittsburgh, PA 15219",
    marketSize: "1.0M users",
    avgGrowth: "40%",
    clientCount: 35,
  },
  // Rhode Island
  {
    id: "pinterest-marketing-agency-rhode-island",
    name: "Rhode Island",
    state: "RI",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "50 Kennedy Plaza, Suite 1500, Providence, RI 02903",
    marketSize: "290K users",
    avgGrowth: "42%",
    clientCount: 17,
  },
  // South Carolina
  {
    id: "pinterest-marketing-agency-south-carolina",
    name: "South Carolina",
    state: "SC",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1 Carillon Lane, Suite 1500, Charleston, SC 29407",
    marketSize: "520K users",
    avgGrowth: "47%",
    clientCount: 24,
  },
  // South Dakota
  {
    id: "pinterest-marketing-agency-south-dakota",
    name: "South Dakota",
    state: "SD",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "200 N Phillips Avenue, Suite 200, Sioux Falls, SD 57104",
    marketSize: "220K users",
    avgGrowth: "43%",
    clientCount: 14,
  },
  // Tennessee - Nashville
  {
    id: "pinterest-marketing-agency-tennessee",
    name: "Tennessee",
    state: "TN",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "222 2nd Avenue North, Suite 240, Nashville, TN 37201",
    marketSize: "1.1M users",
    avgGrowth: "51%",
    clientCount: 38,
  },
  // Tennessee - Memphis
  {
    id: "pinterest-marketing-agency-tennessee-memphis",
    name: "Tennessee",
    state: "TN",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "6075 Poplar Avenue, Suite 800, Memphis, TN 38119",
    marketSize: "720K users",
    avgGrowth: "45%",
    clientCount: 29,
  },
  // Texas - Houston
  {
    id: "pinterest-marketing-agency-texas",
    name: "Texas",
    state: "TX",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1000 Louisiana Street, Suite 5400, Houston, TX 77002",
    marketSize: "3.1M users",
    avgGrowth: "55%",
    clientCount: 81,
  },
  // Texas - Dallas
  {
    id: "pinterest-marketing-agency-texas-dallas",
    name: "Texas",
    state: "TX",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "2100 Ross Avenue, Suite 2700, Dallas, TX 75201",
    marketSize: "2.7M users",
    avgGrowth: "53%",
    clientCount: 75,
  },
  // Texas - Austin
  {
    id: "pinterest-marketing-agency-texas-austin",
    name: "Texas",
    state: "TX",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "654 South Congress, Suite 987, Austin, TX 78704",
    marketSize: "1.3M users",
    avgGrowth: "63%",
    clientCount: 34,
  },
  // Texas - San Antonio
  {
    id: "pinterest-marketing-agency-texas-san-antonio",
    name: "Texas",
    state: "TX",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "112 E Pecan Street, Suite 2400, San Antonio, TX 78205",
    marketSize: "1.5M users",
    avgGrowth: "49%",
    clientCount: 45,
  },
  // Utah
  {
    id: "pinterest-marketing-agency-utah",
    name: "Utah",
    state: "UT",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "136 E South Temple, Suite 1700, Salt Lake City, UT 84111",
    marketSize: "780K users",
    avgGrowth: "57%",
    clientCount: 32,
  },
  // Vermont
  {
    id: "pinterest-marketing-agency-vermont",
    name: "Vermont",
    state: "VT",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "60 Main Street, Suite 100, Burlington, VT 05401",
    marketSize: "180K users",
    avgGrowth: "39%",
    clientCount: 12,
  },
  // Virginia - Virginia Beach
  {
    id: "pinterest-marketing-agency-virginia",
    name: "Virginia",
    state: "VA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "222 Central Park Avenue, Suite 400, Virginia Beach, VA 23462",
    marketSize: "1.2M users",
    avgGrowth: "48%",
    clientCount: 40,
  },
  // Virginia - Richmond
  {
    id: "pinterest-marketing-agency-virginia-richmond",
    name: "Virginia",
    state: "VA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1111 E Main Street, Suite 1600, Richmond, VA 23219",
    marketSize: "820K users",
    avgGrowth: "44%",
    clientCount: 33,
  },
  // Washington
  {
    id: "pinterest-marketing-agency-washington",
    name: "Washington",
    state: "WA",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "987 Pine Street, Suite 234, Seattle, WA 98101",
    marketSize: "1.7M users",
    avgGrowth: "49%",
    clientCount: 56,
  },
  // West Virginia
  {
    id: "pinterest-marketing-agency-west-virginia",
    name: "West Virginia",
    state: "WV",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "300 Summers Street, Suite 1350, Charleston, WV 25301",
    marketSize: "320K users",
    avgGrowth: "37%",
    clientCount: 18,
  },
  // Wisconsin
  {
    id: "pinterest-marketing-agency-wisconsin",
    name: "Wisconsin",
    state: "WI",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "111 E Wisconsin Avenue, Suite 1800, Milwaukee, WI 53202",
    marketSize: "980K users",
    avgGrowth: "42%",
    clientCount: 36,
  },
  // Wyoming
  {
    id: "pinterest-marketing-agency-wyoming",
    name: "Wyoming",
    state: "WY",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "2020 Carey Avenue, Suite 700, Cheyenne, WY 82001",
    marketSize: "150K users",
    avgGrowth: "41%",
    clientCount: 11,
  },
  // Washington DC
  {
    id: "pinterest-marketing-agency-washington-dc",
    name: "Washington DC",
    state: "DC",
    phone: "+8801976927587",
    email: "contact@hello.pinclimb.com",
    address: "1200 17th Street NW, Suite 300, Washington, DC 20036",
    marketSize: "1.8M users",
    avgGrowth: "50%",
    clientCount: 53,
  },
];

// Helper function to get location by ID
export function getLocationById(id: string): Location | undefined {
  return locations.find(location => location.id === id);
}

// Helper function to get all location IDs for static generation
export function getAllLocationIds(): string[] {
  return locations.map(location => location.id);
}